# Generated by Django 2.2.20 on 2021-04-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=1000)),
                ('file_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='food_info',
            field=models.CharField(default='No description', max_length=500),
        ),
    ]
