# Generated by Django 2.2.20 on 2021-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_seat_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('seat', models.CharField(default='[]', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MyTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='', max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
