# Generated by Django 2.2.20 on 2021-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20210412_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_info',
            field=models.CharField(max_length=2000),
        ),
    ]
