# Generated by Django 2.2.20 on 2021-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_mysite_mytickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytickets',
            name='seat',
            field=models.CharField(default='[]', max_length=10000),
        ),
    ]
