# Generated by Django 2.2.20 on 2021-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20210409_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysite',
            name='time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
