# Generated by Django 2.2.20 on 2021-05-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20210412_1633'),
        ('film', '0008_mytickets_user'),
    ]

    operations = [
    ]
