# Generated by Django 2.2.20 on 2021-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20210601_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytickets',
            name='bill_num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
